### ISSUE TITLE
lit-localize breaks property passing in transform mode

### ISSUE THREAD

**Issue by gberaudo** [lit/lit#4544]
### Which package(s) are affected?

Localize (@lit/localize)

### Description

In `transform` mode, lit-localize breaks code using values passed as properties.

Example:
```html
html` <input .placeholder="${msg('Message')}">`
```

becomes:
```html
html `<input .placeholder="Mon message">`
```

which results in `undefined / nothing` being passed as the `placeholder` property (mind the dot in `.placeholder`).

I would expect lit-localize to transform the property `.placeholder` to an attribute `placeholder`.

### Reproduction

I don't have a proper reproduction.

As an illustration, see [this playground](https://lit.dev/playground/#sample=examples%2Fhello-world&project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48Ym9keT5cbiAgPGlucHV0IC5wbGFjZWhvbGRlcj1cIk1vbiBtZXNzYWdlXCI-XG4gIDxpbnB1dCBwbGFjZWhvbGRlcj1cIk1vbiBtZXNzYWdlXCI-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d):
![image](https://github.com/lit/lit/assets/7294662/26ad7b70-4bde-4c8e-be14-1fdaeb3d0faa)

### Workaround

In user code, don't use property but plain attributes (no dot prefix).

Example:
```html
html` <input placeholder="${msg('Message')}">`
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.11.4

### Browser/OS/Node environment

This is not related to the environment.

**Comment by augustjk** [comment]
This should have been fixed with https://github.com/lit/lit/pull/2692
Is your `@lit/localize-tools` up to date?

**Comment by gberaudo** [comment]
Hi @augustjk, thanks for your feedback.
My version is 0.11.4, though not the latest one it was released several months after the PR you mentioned.

Your PR contains these tests:
```js
  checkTransform(
    'html`Hello <b bar=${msg("World", {id: "bar"})}>${"World"}</b>!`;',
    'html`Hello <b bar=${"World"}>World</b>!`;'
  );
```
and later
```js
  checkTransform(
    'html`Hello <b .bar=${msg("World", {id: "bar"})}>${"World"}</b>!`;',
    'html`Hello <b .bar=${"World"}>World</b>!`;'
  );
```

It is not the behaviour I noticed: the replacement is no more an expression. So, with the test data that would become:
```js
html`Hello <b bar="World">World</b>!`
html`Hello <b .bar="World">World</b>!`
```

I just double checked with latest release lit and the issue is still there.
See the reproduction here:
https://github.com/gberaudo/lit-test/blob/master/src/element-input.ts#L9
https://github.com/gberaudo/lit-test/blob/master/localized/fr/element-input.js#L10

**Comment by augustjk** [comment]
Thanks for the reproduction @gberaudo! I can indeed see this is an issue.

What's happening is that the PR mentioned only fixes this if you have the expression that directly follows `=` and we only test for that.

So the following gets rid of the expression during transform resulting in an invalid lit-html template:
```js
html`<b .foo="${msg('World')}">`
```
But doing this without the `"` around the expression preserves it:
```js
html`<b .foo=${msg('World')}>`
```

Quotes around the expression are optional if the expression represents the whole value, which is always the case for property binding.

Maybe it won't be too bad for localize to also look for expressions that are wrapped with the optional quotes.. but removing them from your source code is an easy workaround/fix for now.
